version: '3.8'

services:
  db:
    image: postgres:15.3-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postgres-network
  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: always
  #   env_file:
  #     - .env
  #   ports:
  #     - 15432:80
  #   volumes:
  #     - ./pgadmin_storage:/var/lib/pgadmin/storage
  #   networks:
  #     - postgres-network

networks:
  postgres-network:
    name: postgres-network
